# Generated by Django 5.0.6 on 2024-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_loged_user_alter_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=3000)),
                ('amount_total', models.CharField(max_length=3000)),
                ('payment_intent', models.CharField(max_length=3000)),
            ],
        ),
    ]
