# Generated by Django 5.0.6 on 2024-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_record_payment_id_record_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='customer_email',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
