# Generated by Django 5.0.6 on 2024-09-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_record_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='loged_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
